modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "animal_pen_expansion_naturalist_lite"
version = "${version}"
displayName = "Animal Pen Expansion - Naturalist Lite"
authors = "BONNe1704"
description = '''
Animal Pens Expansion for Naturalist Lite mod.
'''
logoFile = "icon.png"

[[dependencies.animal_pen_expansion_naturalist_lite]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_pen_expansion_naturalist_lite]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_pen_expansion_naturalist_lite]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.animal_pen_expansion_naturalist_lite]]
modId = "animal_pen"
mandatory = true
versionRange = "[2.3.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.animal_pen_expansion_naturalist_lite]]
modId = "naturalist"
mandatory = true
versionRange = "[4.0.0,)"
ordering = "AFTER"
side = "BOTH"