# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.0.0
maven_group = lv.id.bonne
archives_name = animal_pen_expansion_naturalist_lite
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.19
yarn_mappings=1.19+build.4

# Dependencies
architectury_api_version = 5.14.84
fabric_loader_version = 0.16.10
fabric_api_version = 0.58.0+1.19
forge_version = 1.19-41.1.0

animal_pen_fabric_version = 7966911
animal_pen_forge_version = 7966926
naturalist_lite_fabric_version = 3930808
naturalist_lite_forge_version = 3930809
geckolib_fabric_version = 3.1.13
geckolib_forge_version = 3.1.14
cloth_fabric_version=8.3.134
