# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 5.0.0
maven_group = lv.id.bonne
archives_name = animal_pen_expansion_naturalist_lite
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1
yarn_mappings=1.20.1+build.10

# Dependencies
architectury_api_version = 9.2.14
fabric_loader_version = 0.16.10
fabric_api_version = 0.92.2+1.20.1
forge_version = 1.20.1-47.1.3

animal_pen_fabric_version = 7752363
animal_pen_forge_version = 7752366
naturalist_lite_fabric_version = 4847007
naturalist_lite_forge_version = 4847009
geckolib_fabric_version = 1.20.1:4.7
geckolib_forge_version = 1.20.1:4.7
cloth_fabric_version=8.2.88
