# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = lv.id.bonne
archives_name = animal_pen_expansion_naturalist_lite
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.18.2
yarn_mappings=1.18.2+build.3

# Dependencies
architectury_api_version = 4.12.94
fabric_loader_version = 0.16.10
fabric_api_version = 0.77.0+1.18.2
forge_version = 1.18.2-40.1.51

animal_pen_fabric_version = 7752099
animal_pen_forge_version = 7752101
naturalist_lite_fabric_version = 3930805
naturalist_lite_forge_version = 3930806
geckolib_fabric_version = 3.0.54
geckolib_forge_version = 3.0.33
cloth_fabric_version=6.2.62
